In [47]:
import pandas as pd

In [48]:
def read_csv_files(path):
    file =pd.read_csv(path)
    return file

In [49]:
df_mx = read_csv_files(r"C:\Users\JTRUJILLO\Documents\Galgo\Scripts\Otros\homologar_modelos\pages\KTM\MX\Homologación KTM - KTM - MX.csv")

In [50]:
df_co = read_csv_files(r"C:\Users\JTRUJILLO\Documents\Galgo\Scripts\Otros\homologar_modelos\pages\KTM\CO\CO-KTM_sugeridos-FINAL.csv")

In [51]:
df_cl = read_csv_files(r"C:\Users\JTRUJILLO\Documents\Galgo\Scripts\Otros\homologar_modelos\pages\KTM\CL\CL-KTM_sugeridos-FINAL.csv")

In [52]:
def actualizar_modelo_sugerido(df):
    """
    Función que actualiza la columna modelo_sugerido usando el valor de Aux
    cuando modelo_sugerido es igual a 'No encontrado' y agrega una columna
    que indica si el registro fue modificado. También crea una columna modelo_final
    con los caracteres especiales reemplazados por espacios
    """
    # Crear una copia del dataframe para no modificar el original
    df_actualizado = df.copy()

    # Crear columna para indicar si fue modificado
    df_actualizado['fue_modificado'] = df_actualizado['modelo_sugerido'] == 'No encontrado'

    # Aplicar la lógica: si modelo_sugerido es 'No encontrado', usar el valor de Aux
    df_actualizado['modelo_sugerido'] = df_actualizado.apply(
        lambda row: row['Aux'] if row['modelo_sugerido'] == 'No encontrado' else row['modelo_sugerido'],
        axis=1
    )

    # Crear columna modelo_final reemplazando caracteres especiales por espacios
    df_actualizado['modelo_final'] = df_actualizado['modelo_sugerido'].str.replace('-', ' ', regex=False)

    return df_actualizado

In [53]:
# Aplicar la función a los dataframes
df_mx_actualizado = actualizar_modelo_sugerido(df_mx)
df_co_actualizado = actualizar_modelo_sugerido(df_co)
df_cl_actualizado = actualizar_modelo_sugerido(df_cl)

In [62]:
columns = ["code_modelos_agrupados", "Modelo", "modelo_final"]

In [63]:
df_co_actualizado = df_co_actualizado[columns]
df_mx_actualizado = df_mx_actualizado[columns]
df_cl_actualizado = df_cl_actualizado[columns]

In [64]:
df_cl_actualizado

        code_modelos_agrupados             Modelo   modelo_final
0  CL599-ktm-390-adventure-abs  390 Adventure ABS  390 Adventure
1            CL34-ktm-duke-200       Duke 200 ABS       200 Duke
2           CL601-ktm-duke-250           Duke 250       250 Duke

In [65]:
df_mx_actualizado

,code_modelos_agrupados,Modelo,modelo_final
0,MX1235-ktm-150-xc-2023,150 XC,150 XC W
1,MX1225-ktm-sx-125-2023,SX 125,125 SX
2,MX1231-ktm-1290-super-adventure-s-2023,1290 Super Adventure S,1290 Super Adventure S
3,MX710-ktm-rc-200,RC 200,RC 200
4,MX1222-ktm-250-sx-f,250 SX-F,250 SX F
5,MX1200-ktm-250-adventure-2023,250 Adventure,250 Adventure
6,MX713-ktm-rc-390-abs,RC 390 ABS,RC 390
7,MX714-ktm-390-adventure-abs,390 Adventure ABS,390 Adventure SW

In [66]:
df_co_actualizado

,code_modelos_agrupados,Modelo,modelo_final
0,CO2402-ktm-rc-390-gp,RC 390 GP,RC 390 GP
1,CO2795-ktm-250-duke,250 Duke,250 Duke
2,CO1609-ktm-690-enduro-r-2024,690 Enduro R,690 Enduro R
3,CO2399-ktm-rc-200-gp,RC 200,RC 200
4,CO1397-ktm-390-duke-ng-2024,390 Duke NG,390 Duke
5,CO1608-ktm-450-smr-2024,450 SMR,450 SMR
6,CO833-ktm-200-duke-ng-blanca,200 Duke Gen2 ABS,200 Duke
7,CO2929-ktm-200-duke-wo,200 Duke WO,200 Duke WO
8,CO1396-ktm-200-duke-generacion-1-2024,200 Duke Gen2,NaN
9,CO1606-ktm-250-exc-2024,250 EXC,250 EXC
10,CO1401-ktm-rc-390-2024,RC 390,RC 390
11,CO1610-ktm-890-duke-r-2023,890 Duke R,NaN
12,CO1399-ktm-390-adventure-2024,390 Adventure,390 Adventure
13,CO1398-ktm-250-adventure-2024,250 Adventure,250 Adventure
14,CO1607-ktm-300-exc-2024,300 EXC,300 EXC
15,CO1375-ktm-1290-super-adventure,1290 Super Adventure,1290 Super Adventure S

In [94]:
# # Renombrar las columnas para distinguirlas por país
# df_cl_renamed = df_cl_actualizado.rename(columns={
#     'code_modelos_agrupados': 'code_modelos_agrupados_cl',
#     'Modelo': 'Modelo_cl'
# })

# df_mx_renamed = df_mx_actualizado.rename(columns={
#     'code_modelos_agrupados': 'code_modelos_agrupados_mx',
#     'Modelo': 'Modelo_mx'
# })

# df_co_renamed = df_co_actualizado.rename(columns={
#     'code_modelos_agrupados': 'code_modelos_agrupados_co',
#     'Modelo': 'Modelo_co'
# })

# # Hacer merge de los 3 dataframes incluyendo las columnas de Modelo
# df_unificado = df_cl_renamed[['modelo_final', 'code_modelos_agrupados_cl', 'Modelo_cl']].merge(
#     df_mx_renamed[['modelo_final', 'code_modelos_agrupados_mx', 'Modelo_mx']],
#     on='modelo_final',
#     how='outer'
# ).merge(
#     df_co_renamed[['modelo_final', 'code_modelos_agrupados_co', 'Modelo_co']],
#     on='modelo_final',
#     how='outer'
# )

In [95]:
# Recopilar TODOS los modelos originales de todos los países
todos_modelos_originales = []

# Colombia
if not df_co_actualizado.empty:
    co_modelos = df_co_actualizado[['Modelo', 'modelo_final', 'code_modelos_agrupados']].copy()
    co_modelos.columns = ['modelo_original', 'modelo_final', 'code_modelos_agrupados']
    co_modelos['pais'] = 'CO'
    todos_modelos_originales.append(co_modelos)

# México
if not df_mx_actualizado.empty:
    mx_modelos = df_mx_actualizado[['Modelo', 'modelo_final', 'code_modelos_agrupados']].copy()
    mx_modelos.columns = ['modelo_original', 'modelo_final', 'code_modelos_agrupados']
    mx_modelos['pais'] = 'MX'
    todos_modelos_originales.append(mx_modelos)

# Chile
if not df_cl_actualizado.empty:
    cl_modelos = df_cl_actualizado[['Modelo', 'modelo_final', 'code_modelos_agrupados']].copy()
    cl_modelos.columns = ['modelo_original', 'modelo_final', 'code_modelos_agrupados']
    cl_modelos['pais'] = 'CL'
    todos_modelos_originales.append(cl_modelos)

# Concatenar todos
df_todos_modelos = pd.concat(todos_modelos_originales, ignore_index=True)

In [101]:
# Crear una clave única que combine modelo_original Y modelo_final
def crear_clave_unica(row):
    """Crea una clave única para cada modelo"""
    original = str(row['modelo_original']).strip()
    final = str(row['modelo_final']).strip()

    # Si modelo_final es válido, usarlo; sino usar original
    if final and final != 'nan' and final != 'No encontrado':
        return final
    else:
        return original

df_todos_modelos['clave_modelo'] = df_todos_modelos.apply(crear_clave_unica, axis=1)

# Obtener todas las claves únicas
claves_unicas = df_todos_modelos['clave_modelo'].unique()
print(f"Total de modelos únicos: {len(claves_unicas)}")

# Crear matriz pivoteada
df_unificado = df_todos_modelos.pivot_table(
    index='clave_modelo',
    columns='pais',
    values=['modelo_original', 'code_modelos_agrupados'],
    aggfunc='first'  # En caso de duplicados, tomar el primero
).reset_index()

# Aplanar columnas multi-nivel
df_unificado.columns = [
    'modelo_unificado',
    'code_cl', 'code_co', 'code_mx',  # codes
    'original_cl', 'original_co', 'original_mx'  # originales
]

Total de modelos únicos: 20

In [102]:
df_unificado

,modelo_unificado,code_cl,code_co,code_mx,original_cl,original_co,original_mx
0,125 SX,NaN,NaN,MX1225-ktm-sx-125-2023,NaN,NaN,SX 125
1,1290 Super Adventure S,NaN,CO1375-ktm-1290-super-adventure,MX1231-ktm-1290-super-adventure-s-2023,NaN,1290 Super Adventure,1290 Super Adventure S
2,150 XC W,NaN,NaN,MX1235-ktm-150-xc-2023,NaN,NaN,150 XC
3,200 Duke,CL34-ktm-duke-200,CO833-ktm-200-duke-ng-blanca,NaN,Duke 200 ABS,200 Duke Gen2 ABS,NaN
4,200 Duke Gen2,NaN,CO1396-ktm-200-duke-generacion-1-2024,NaN,NaN,200 Duke Gen2,NaN
5,200 Duke WO,NaN,CO2929-ktm-200-duke-wo,NaN,NaN,200 Duke WO,NaN
6,250 Adventure,NaN,CO1398-ktm-250-adventure-2024,MX1200-ktm-250-adventure-2023,NaN,250 Adventure,250 Adventure
7,250 Duke,CL601-ktm-duke-250,CO2795-ktm-250-duke,NaN,Duke 250,250 Duke,NaN
8,250 EXC,NaN,CO1606-ktm-250-exc-2024,NaN,NaN,250 EXC,NaN
9,250 SX F,NaN,NaN,MX1222-ktm-250-sx-f,NaN,NaN,250 SX-F
10,300 EXC,NaN,CO1607-ktm-300-exc-2024,NaN,NaN,300 EXC,NaN
11,390 Adventure,CL599-ktm-390-adventure-abs,CO1399-ktm-390-adventure-2024,NaN,390 Adventure ABS,390 Adventure,NaN
12,390 Adventure SW,NaN,NaN,MX714-ktm-390-adventure-abs,NaN,NaN,390 Adventure ABS
13,390 Duke,NaN,CO1397-ktm-390-duke-ng-2024,NaN,NaN,390 Duke NG,NaN
14,450 SMR,NaN,CO1608-ktm-450-smr-2024,NaN,NaN,450 SMR,NaN
15,690 Enduro R,NaN,CO1609-ktm-690-enduro-r-2024,NaN,NaN,690 Enduro R,NaN
16,890 Duke R,NaN,CO1610-ktm-890-duke-r-2023,NaN,NaN,890 Duke R,NaN
17,RC 200,NaN,CO2399-ktm-rc-200-gp,MX710-ktm-rc-200,NaN,RC 200,RC 200
18,RC 390,NaN,CO1401-ktm-rc-390-2024,MX713-ktm-rc-390-abs,NaN,RC 390,RC 390 ABS
19,RC 390 GP,NaN,CO2402-ktm-rc-390-gp,NaN,NaN,RC 390 GP,NaN

In [103]:
df_unificado.columns

Index(['modelo_unificado', 'code_cl', 'code_co', 'code_mx', 'original_cl',
       'original_co', 'original_mx'],
      dtype='object')

In [109]:
df_unificado.rename(columns={"modelo_unificado": "modelo_final", "original_cl": "Modelo_cl", "original_mx": "Modelo_mx", "original_co": "Modelo_co",}, inplace=True)

In [110]:
df_unificado

,modelo_final,code_cl,code_co,code_mx,Modelo_cl,Modelo_co,Modelo_mx
0,125 SX,NaN,NaN,MX1225-ktm-sx-125-2023,NaN,NaN,SX 125
1,1290 Super Adventure S,NaN,CO1375-ktm-1290-super-adventure,MX1231-ktm-1290-super-adventure-s-2023,NaN,1290 Super Adventure,1290 Super Adventure S
2,150 XC W,NaN,NaN,MX1235-ktm-150-xc-2023,NaN,NaN,150 XC
3,200 Duke,CL34-ktm-duke-200,CO833-ktm-200-duke-ng-blanca,NaN,Duke 200 ABS,200 Duke Gen2 ABS,NaN
4,200 Duke Gen2,NaN,CO1396-ktm-200-duke-generacion-1-2024,NaN,NaN,200 Duke Gen2,NaN
5,200 Duke WO,NaN,CO2929-ktm-200-duke-wo,NaN,NaN,200 Duke WO,NaN
6,250 Adventure,NaN,CO1398-ktm-250-adventure-2024,MX1200-ktm-250-adventure-2023,NaN,250 Adventure,250 Adventure
7,250 Duke,CL601-ktm-duke-250,CO2795-ktm-250-duke,NaN,Duke 250,250 Duke,NaN
8,250 EXC,NaN,CO1606-ktm-250-exc-2024,NaN,NaN,250 EXC,NaN
9,250 SX F,NaN,NaN,MX1222-ktm-250-sx-f,NaN,NaN,250 SX-F
10,300 EXC,NaN,CO1607-ktm-300-exc-2024,NaN,NaN,300 EXC,NaN
11,390 Adventure,CL599-ktm-390-adventure-abs,CO1399-ktm-390-adventure-2024,NaN,390 Adventure ABS,390 Adventure,NaN
12,390 Adventure SW,NaN,NaN,MX714-ktm-390-adventure-abs,NaN,NaN,390 Adventure ABS
13,390 Duke,NaN,CO1397-ktm-390-duke-ng-2024,NaN,NaN,390 Duke NG,NaN
14,450 SMR,NaN,CO1608-ktm-450-smr-2024,NaN,NaN,450 SMR,NaN
15,690 Enduro R,NaN,CO1609-ktm-690-enduro-r-2024,NaN,NaN,690 Enduro R,NaN
16,890 Duke R,NaN,CO1610-ktm-890-duke-r-2023,NaN,NaN,890 Duke R,NaN
17,RC 200,NaN,CO2399-ktm-rc-200-gp,MX710-ktm-rc-200,NaN,RC 200,RC 200
18,RC 390,NaN,CO1401-ktm-rc-390-2024,MX713-ktm-rc-390-abs,NaN,RC 390,RC 390 ABS
19,RC 390 GP,NaN,CO2402-ktm-rc-390-gp,NaN,NaN,RC 390 GP,NaN

In [ ]:
df_unificado = df_unificado[["modelo_final", "Modelo_cl", "Modelo_mx", "Modelo_co", "code_mx", "code_cl", "code_co"]]

In [114]:
# df_unificado = df_unificado[["modelo_final", "Modelo_cl", "Modelo_mx", "Modelo_co", "code_modelos_agrupados_cl", "code_modelos_agrupados_mx", "code_modelos_agrupados_co"]]

In [115]:
df_unificado_excel = df_unificado.fillna("No disponible")

In [117]:
df_unificado_excel['disponible_en'] = df_unificado_excel.apply(
    lambda row: ', '.join([
        'Chile' if pd.notna(row['code_cl']) and row['code_cl'] != 'No disponible' else '',
        'México' if pd.notna(row['code_mx']) and row['code_mx'] != 'No disponible' else '',
        'Colombia' if pd.notna(row['code_co']) and row['code_co'] != 'No disponible' else ''
    ]).strip(', '), axis=1
)

# Función para verificar si necesita homologación y en qué países
def verificar_homologacion(row):
    modelo_final = row['modelo_final']
    modelo_cl = row['Modelo_cl']
    modelo_mx = row['Modelo_mx']
    modelo_co = row['Modelo_co']

    paises_para_homologar = []

    # Verificar Chile
    if modelo_cl != 'No disponible' and modelo_cl != modelo_final:
        paises_para_homologar.append('Chile')

    # Verificar México
    if modelo_mx != 'No disponible' and modelo_mx != modelo_final:
        paises_para_homologar.append('México')

    # Verificar Colombia
    if modelo_co != 'No disponible' and modelo_co != modelo_final:
        paises_para_homologar.append('Colombia')

    if paises_para_homologar:
        return ', '.join(paises_para_homologar)
    else:
        return 'No necesita'

# Aplicar la función para determinar homologación
df_unificado_excel['necesita_homologacion'] = df_unificado_excel.apply(verificar_homologacion, axis=1)

In [118]:
df_unificado_excel

,modelo_final,Modelo_cl,Modelo_mx,Modelo_co,code_mx,code_cl,code_co,disponible_en,necesita_homologacion
0,125 SX,No disponible,SX 125,No disponible,MX1225-ktm-sx-125-2023,No disponible,No disponible,México,México
1,1290 Super Adventure S,No disponible,1290 Super Adventure S,1290 Super Adventure,MX1231-ktm-1290-super-adventure-s-2023,No disponible,CO1375-ktm-1290-super-adventure,"México, Colombia",Colombia
2,150 XC W,No disponible,150 XC,No disponible,MX1235-ktm-150-xc-2023,No disponible,No disponible,México,México
3,200 Duke,Duke 200 ABS,No disponible,200 Duke Gen2 ABS,No disponible,CL34-ktm-duke-200,CO833-ktm-200-duke-ng-blanca,"Chile, , Colombia","Chile, Colombia"
4,200 Duke Gen2,No disponible,No disponible,200 Duke Gen2,No disponible,No disponible,CO1396-ktm-200-duke-generacion-1-2024,Colombia,No necesita
5,200 Duke WO,No disponible,No disponible,200 Duke WO,No disponible,No disponible,CO2929-ktm-200-duke-wo,Colombia,No necesita
6,250 Adventure,No disponible,250 Adventure,250 Adventure,MX1200-ktm-250-adventure-2023,No disponible,CO1398-ktm-250-adventure-2024,"México, Colombia",No necesita
7,250 Duke,Duke 250,No disponible,250 Duke,No disponible,CL601-ktm-duke-250,CO2795-ktm-250-duke,"Chile, , Colombia",Chile
8,250 EXC,No disponible,No disponible,250 EXC,No disponible,No disponible,CO1606-ktm-250-exc-2024,Colombia,No necesita
9,250 SX F,No disponible,250 SX-F,No disponible,MX1222-ktm-250-sx-f,No disponible,No disponible,México,México
10,300 EXC,No disponible,No disponible,300 EXC,No disponible,No disponible,CO1607-ktm-300-exc-2024,Colombia,No necesita
11,390 Adventure,390 Adventure ABS,No disponible,390 Adventure,No disponible,CL599-ktm-390-adventure-abs,CO1399-ktm-390-adventure-2024,"Chile, , Colombia",Chile
12,390 Adventure SW,No disponible,390 Adventure ABS,No disponible,MX714-ktm-390-adventure-abs,No disponible,No disponible,México,México
13,390 Duke,No disponible,No disponible,390 Duke NG,No disponible,No disponible,CO1397-ktm-390-duke-ng-2024,Colombia,Colombia
14,450 SMR,No disponible,No disponible,450 SMR,No disponible,No disponible,CO1608-ktm-450-smr-2024,Colombia,No necesita
15,690 Enduro R,No disponible,No disponible,690 Enduro R,No disponible,No disponible,CO1609-ktm-690-enduro-r-2024,Colombia,No necesita
16,890 Duke R,No disponible,No disponible,890 Duke R,No disponible,No disponible,CO1610-ktm-890-duke-r-2023,Colombia,No necesita
17,RC 200,No disponible,RC 200,RC 200,MX710-ktm-rc-200,No disponible,CO2399-ktm-rc-200-gp,"México, Colombia",No necesita
18,RC 390,No disponible,RC 390 ABS,RC 390,MX713-ktm-rc-390-abs,No disponible,CO1401-ktm-rc-390-2024,"México, Colombia",México
19,RC 390 GP,No disponible,No disponible,RC 390 GP,No disponible,No disponible,CO2402-ktm-rc-390-gp,Colombia,No necesita

In [119]:
df_unificado_excel.to_csv("KTM_homologacion.csv", index=False)